alias l='ls -lah'
lsym () { find $1 -maxdepth 1 -type l -ls; }
alias c='cd'
alias d='cd ..'
alias ipa="hostname -I"
alias pys="python -m SimpleHTTPServer 8888"

subl () { "/mnt/c/Program Files/Sublime Text 3/sublime_text.exe" "$@" & }
alias mysq="sudo mysql -u root -p"

alias dce="docker compose exec"
alias dcu="docker-compose up -d"
alias dex="docker exec -it $1 bash"
alias dlg="docker logs -f"
alias dps="docker ps"
alias dpsa="docker ps -a"

alias be="bundle exec"
alias rs="bundle exec ./bin/rails server"
alias rc="bundle exec ./bin/rails console"
alias rr="bundle exec ./bin/rake routes"
alias rrr="rm tmp/routes.txt && touch tmp/routes.txt && bundle exec ./bin/rake routes >> tmp/routes.txt && vi tmp/routes.txt"

alias gita="git add ."
alias gits="git status"
alias gitps="git push"
alias gitc="git commit -am"
alias gitl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gitb="git branch"
alias gitba="git branch -a"
alias gitbr="git branch -r"
alias giti="!([ ! -e .gitignore ] && touch .gitignore) | echo $1 >>.gitignore"
alias gitnb="git checkout -b"
alias gitd="git diff"
alias gitco="git checkout"
alias gitumb="git branch --no-merged"
alias gitmb="git branch --merged"
alias gitau="git update-index --assume-unchanged"
alias gitac="git update-index --no-assume-unchanged"
