# aliases
alias l='ls -lah'
alias c='cd'
alias d='cd ..'

alias be="bundle exec"
alias rs="bundle exec rails server -b 0.0.0.0"
alias ru="bundle exec rackup"
alias rc="bundle exec rails console"
alias rr="bundle exec rake routes"
alias rrr="rm tmp/routes.txt && touch tmp/routes.txt && bundle exec rake routes >> tmp/routes.txt && vi tmp/routes.txt"
alias rbs="browser-sync start --files 'app/assets/stylesheets/*.scss, app/views/*.html.erb' --no-open --proxy"
alias restart="touch tmp/restart.txt"
alias pss="passenger start"
alias sshserv="ruby ~/server.rb"

alias psq="sudo -u postgres psql"
alias rndFile="dd if=/dev/zero of=testfile.txt count=1 bs="
alias pys="python -m SimpleHTTPServer 3100"

alias opt="optipng ~/workspace/x/*.png && svgo ~/workspace/x/*.svg"
alias subl="~/sublime_text_3/sublime_text"
alias subm="~/sublime_merge/sublime_merge"
alias code="~/vscode/code"
alias nvmu="nvm use"
alias ipa="hostname -I"

alias gita="git add ."
alias gits="git status"
alias gitps="git push"
alias gitc="git commit -am"
alias gitl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gitb="git branch"
alias gitba="git branch -a"
alias gitbr="git branch -r"
alias giti="!([ ! -e .gitignore ] && touch .gitignore) | echo $1 >>.gitignore"
alias gitnb="git checkout -b"
alias gitd="git diff"
alias gitco="git checkout"
alias gitumb="git branch --no-merged"
alias gitmb="git branch --merged"

alias gitau="git update-index --assume-unchanged"
alias gitac="git update-index --no-assume-unchanged"

